TwitterDjango/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include  # url()
from django.views.generic import TemplateView
from django.views.static import serve

from article.views import home_view
from hotsearch.views import hot_search_list

urlpatterns = [
    path('', home_view, name='home'),
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('admin/', admin.site.urls),
    path('api/articles/', include(('article.urls', 'article'), namespace='article')),
    path('api/user/', include(('account.urls', 'account'), namespace='user')),
    path('api/profile/', include(('userprofile.urls', 'userprofile'), namespace='profile')),
    path('api/hotsearch', hot_search_list),
    re_path(r'.*', TemplateView.as_view(template_name='index.html'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path

from .views import (user_login,
                    user_logout,
                    user_register, user_change_password, send_reset_email, reset_password_2)

urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
    path('changepwd/', user_change_password, name='changepwd'),
    path('forgetpwd/', send_reset_email),
    path('resetpwd/', reset_password_2, name='reset')
]

tweetme2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include  # url()
from django.views.generic import TemplateView

from article.views import home_view

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    path('api/articles/', include(('article.urls', 'article'), namespace='article')),
    path('api/user/', include(('account.urls', 'account'), namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/components/article_item.html
<template id="article-item">
    {% verbatim vue4 %}
    <div :data="articleList">
        <div class="box mb-3 shadow-sm border rounded bg-white osahan-post">
            <div class="p-3 d-flex align-items-center border-bottom osahan-post-header">
                <div class="dropdown-list-image mr-3">
                    <img alt="" class="rounded-circle" src="#">
                    <div class="status-indicator bg-success"></div>
                </div>
                <div class="font-weight-bold">
                    <div class="text-truncate">USERNAME</div>
                    <div class="small text-gray-500">PhoneNum</div>
                </div>
                <span class="ml-auto small">TimeStamp</span>
            </div>
            <div class="p-3 border-bottom osahan-post-body">
                <p><template slot-scope="slot">{{ slot.row.pk }}</template></p>
            </div>
            <div class="p-3 osahan-post-footer">
                <a href="#" class="mr-3 text-secondary"><i
                        class="feather-heart text-danger"></i>1
                </a>
                <a href="#" data-toggle="modal" data-target="#"
                   class="mr-3 text-secondary"><i
                        class="feather-message-square"></i>2
                </a>
                <a href="#" class=" mr-3 text-secondary"><i class="feather-share-2"></i>2</a>
            </div>
        </div>
    </div>
{% endverbatim vue4 %}
</template>

templates/components/comment_modal.html
{% load static %}
{% verbatim vue2 %}
<div class="modal fade" id="dialog{{ article.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content d-flex box mb-3 shadow-sm border rounded osahan-post" style="width: 150%">
                <div class="box mb-3 shadow-sm border rounded bg-white osahan-post">
                    <div class="p-3 d-flex align-items-center border-bottom osahan-post-header">
                        <div class="dropdown-list-image mr-3">
                            <img alt="" class="rounded-circle" src={{ article.author.user_avatar }}>
                            <div class="status-indicator bg-success"></div>
                        </div>
                        <div class="font-weight-bold">
                            <div class="text-truncate">{{ article.author.username }}</div>
                            <div class="small text-gray-500">{{ article.author.phone_number }}</div>
                        </div>
                        <span class="ml-auto small">3 hours</span>
                    </div>
                    <div class="p-3 border-bottom osahan-post-body">
                        <p>{{ article.content }}<a href="#">{{ article.tags_list }}</a></p>
                        {% if article.image %}
                            <img class="img-fluid" alt="Responsive image" src="{{ article.image }}">
                        {% endif %}
                    </div>

                    <div v-for="comment in commentList"
                         class="p-3   border-bottom osahan-post-comment">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" alt="" src={% static 'img/p7.png' %}>
                            <div class="status-indicator bg-success"></div>
                        </div>
                        <div class="font-weight-bold">
                            <div class="text-truncate">
                                {% verbatim vue %}{{ comment.author.username }} {% endverbatim vue %}<span
                                    class="float-right small">2 min</span>
                            </div>
                            <div class="small text-gray-500">
                                {% verbatim vue %}{{ comment.content }} {% endverbatim vue %}
                            </div>
                        </div>
                    </div>

                    <div class="p-3">
                        <div class="p-3 w-100">
                    <textarea placeholder="你的想法..." id="comment_content" class="form-control border-0 p-0 shadow-none"
                              rows="2" ></textarea>
                        </div>
                        <div class="border-top p-3 d-flex align-items-center">
                            <div class="mr-auto"></div>
                            <div class="flex-shrink-1">
                                <button type="button" id="comment_btn"
                                        v-on:click="postComment({{ article.pk }},document.getElementById('comment_content').value)"
                                        class="btn btn-primary btn-sm"> &emsp;评论&emsp;
                                </button>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.modal-content -->
            </div><!-- /.modal -->
        </div>
    </div>
{% endverbatim vue2 %}

templates/components/form.html
<form method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='btn btn-secondary'>{% if btn_label %}
        {{btn_label}} {% else %}Save{% endif %}</button>
</form>

templates/components/navbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-dark bg-dark  osahan-nav-top p-0">
        <div class="container">
            <!--图标和搜索框//TODO-->
            <a class="navbar-brand mr-2" href="{% url 'home' %}"><img style="width:38px;height: 38px;" alt=""
                                                                       src={% static 'img/logo1.png' %}>
            </a>
            <form class="d-none d-sm-inline-block form-inline mr-auto my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text" class="form-control shadow-none border-0" placeholder="搜索博客"
                           aria-label="Search"  aria-describedby="basic-addon2" id="search-txt">
                    <div class="input-group-append">
                        <a href="#"><!--//TODO 找出searchbar回车键的问题-->
                            <button class="btn" type="button">
                                <i class="feather-search"></i>
                            </button>
                        </a>
                    </div>
                </div>
            </form>
            <!--顶部状态栏//TODO-->
            <ul class="navbar-nav ml-auto d-flex align-items-center">
                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="feather-search mr-2"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow-sm animated--grow-in"
                         aria-labelledby="searchDropdown">
                        <form class="form-inline mr-auto w-100 navbar-search">
                            <div class="input-group">
                                <input type="text" class="form-control border-0 shadow-none"
                                       placeholder="Search blog..." aria-label="Search" aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                    <button class="btn" type="button">
                                        <i class="feather-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="jobs.html"><i class="feather-user mr-2"></i><span
                            class="d-none d-lg-inline">个人中心</span></a>
                </li>
                <li class="nav-item dropdown mr-2">
                    <a class="nav-link dropdown-toggle pr-0" href="#" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="feather-file-text mr-2"></i><span class="d-none d-lg-inline">Pages</span>
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow-sm">
                        <a class="dropdown-item" href="jobs.html"><i class="feather-briefcase mr-1"></i> Jobs</a>
                        <a class="dropdown-item" href="profile.html"><i class="feather-user mr-1"></i> Profile</a>
                        <a class="dropdown-item" href="connection.html"><i class="feather-users mr-1"></i>
                            Connection</a>
                        <a class="dropdown-item" href="company-profile.html"><i class="feather-user-plus mr-1"></i>
                            Company Profile</a>
                        <a class="dropdown-item" href="job-profile.html"><i class="feather-globe mr-1"></i> Job Profile</a>
                        <a class="dropdown-item" href="user/sign-in.html"><i class="feather-log-in mr-1"></i> Sign
                            In</a>
                        <a class="dropdown-item" href="user/sign-up.html"><i class="feather-lock mr-1"></i> Sign Up</a>
                    </div>
                </li>
                <li class="nav-item dropdown no-arrow mx-1 osahan-list-dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="feather-message-square"></i>
                        <!-- Counter - Alerts -->
                        <span class="badge badge-danger badge-counter">8</span>
                    </a>
                    <!-- Dropdown - Alerts -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow-sm">
                        <h6 class="dropdown-header">
                            Message Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img alt="" class="rounded-circle" src={% static 'img/p1.png' %}>
                                <div class="status-indicator bg-success"></div>
                            </div>
                            <div class="font-weight-bold overflow-hidden">
                                <div class="text-truncate">Hi there! I am wondering if you can help me with a problem
                                    I've been having.
                                </div>
                                <div class="small text-gray-500">Emily Fowler · 58m</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img alt="" class="rounded-circle" src={% static 'img/p2.png' %}>
                                <div class="status-indicator"></div>
                            </div>
                            <div class="overflow-hidden">
                                <div class="text-truncate">I have the photos that you ordered last month, how would you
                                    like them sent to you?
                                </div>
                                <div class="small text-gray-500">Jae Chun · 1d</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img alt="" class="rounded-circle" src={% static 'img/p3.png' %} >
                                <div class="status-indicator bg-warning"></div>
                            </div>
                            <div class="overflow-hidden">
                                <div class="text-truncate">Last month's report looks great, I am very happy with the
                                    progress so far, keep up the good work!
                                </div>
                                <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="dropdown-list-image mr-3">
                                <img alt="" class="rounded-circle" src={% static 'img/p4.png' %} >
                                <div class="status-indicator bg-success"></div>
                            </div>
                            <div class="overflow-hidden">
                                <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me
                                    that people say this to all dogs, even if they aren't good...
                                </div>
                                <div class="small text-gray-500">Chicken the Dog · 2w</div>
                            </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                    </div>
                </li>
                <li class="nav-item dropdown no-arrow mx-1 osahan-list-dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="feather-bell"></i>
                        <!-- Counter - Alerts -->
                        <span class="badge badge-info badge-counter">6</span>
                    </a>
                    <!-- Dropdown - Alerts -->
                    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow-sm">
                        <h6 class="dropdown-header">
                            Alerts Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-primary">
                                    <i class="feather-download-cloud text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 12, 2019</div>
                                <span class="font-weight-bold">A new monthly report is ready to download!</span>
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-success">
                                    <i class="feather-edit text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 7, 2019</div>
                                $290.29 has been deposited into your account!
                            </div>
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-warning">
                                    <i class="feather-folder text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 2, 2019</div>
                                Spending Alert: We've noticed unusually high spending for your account.
                            </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                    </div>
                </li>
                <!-- Nav Item - User Information -->
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown no-arrow ml-1 osahan-profile-dropdown">
                        <a class="nav-link dropdown-toggle pr-0" href="#" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <img class="img-profile rounded-circle"
                                 src="https://danbooru.donmai.us/data/__original_drawn_by_kuroi_liar_player__2008844c97e06f63037267367d206e97.jpg">
                        </a>
                        <!-- Dropdown - User Information -->

                        <div class="dropdown-menu dropdown-menu-right shadow-sm">
                            <div class="p-3 d-flex align-items-center">
                                <div class="dropdown-list-image mr-3">
                                    <img alt="" class="rounded-circle"
                                         src="https://danbooru.donmai.us/data/__original_drawn_by_kuroi_liar_player__2008844c97e06f63037267367d206e97.jpg">
                                    <div class="status-indicator bg-success"></div>
                                </div>
                                <div class="font-weight-bold">
                                    <div class="text-truncate">{{ request.session.username }}</div>
                                    <div class="small text-gray-500">User</div>
                                </div>
                            </div>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'user:center' %}"><i class="feather-user mr-1"></i>
                                个人信息</a>
                            <a class="dropdown-item" href="{% url 'user:logout' %}"><i class="feather-log-out mr-1"></i>登出</a>
                        </div>
                    </li>
                {% else %}
                    <a href="{% url 'user:login' %}">
                        <button class="btn btn-primary btn-block text-uppercase">登录</button>
                    </a>
                {% endif %}

            </ul>
        </div>
    </nav>

templates/components/post_form.html
<form action="/api/articles/create/" method="POST">{% csrf_token %}
    <div class="box shadow-sm border rounded bg-white mb-3 osahan-share-post">
        <input type="hidden" name="user" value="{{ request.user.id }}">
        <ul class="nav nav-justified border-bottom osahan-line-tab" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="contact-tab" data-toggle="tab" href="#contact" role="tab"
                   aria-controls="contact" aria-selected="false"><i class="feather-clipboard"></i> 发布微博</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                   aria-controls="profile" aria-selected="false"><i class="feather-image"></i>上传图片</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane show active" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                <div class="p-3 w-100">
                    <textarea placeholder="你的想法..." class="form-control border-0 p-0 shadow-none"
                              rows="4"
                              name="content"></textarea>
                </div>
            </div>
            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <div class="p-3 w-100 text-center">
                    <!--//TODO 改成上传图片-->
                    <a href="">
                        <input type="file" accept="images/*" class=" form-control  shadow-none border-0 p-0">
                    </a>
                </div>
            </div>

        </div>
        <div class="border-top p-3 d-flex align-items-center">
            <div class="mr-auto"><a href="#" class="text-link small"><i class="feather-tag"></i> 添加tag</a>
            </div>
            <div class="flex-shrink-1">
                <button type="submit"
                        {% if not request.user.is_authenticated %}disabled{% endif %}
                        class="btn btn-primary btn-sm">&emsp;发布&emsp;</button>
            </div>
        </div>
    </div>
</form>

templates/components/user_aside.html
{% if request.user.is_authenticated %}
        <div class="box mb-3 shadow-sm border rounded bg-white profile-box text-center">
            <div class="py-4 px-3 border-bottom">
                <img class="img-fluid mt-2 rounded-circle" alt="Responsive image"
                     src="{{ request.session.user_avatar }}">
                <h5 class="font-weight-bold text-dark mb-1 mt-4">{{ request.session.username }}</h5>
                <p class="mb-0 text-muted">User</p>
            </div>
            <div class="box p-3 border-bottom">
                <p>{{ request.session.desc }}</p>
            </div>
            <div class="d-flex">
                <div class="col-6 border-right p-3">
                    <h6 class="font-weight-bold text-dark mb-1">{% if request.session.fanscount %}
                        {{ request.session.blogcount }}
                    {% else %}0{% endif %} </h6>
                    <p class="mb-0 text-black-50 small">粉丝数</p>
                </div>
                <div class="col-6 p-3">
                    <h6 class="font-weight-bold text-dark mb-1">{{ articles.count }} </h6>
                    <p class="mb-0 text-black-50 small">微博数</p>
                </div>
            </div>
            <!--  -->
            <div class="overflow-hidden border-top">
                <a class="font-weight-bold p-3 d-block" href="profile.html">个人中心</a>
            </div>
        </div>
    {% else %}
        <div class="box mb-3 shadow-sm border rounded bg-white profile-box text-center">
            <div class="py-4 px-3 border-bottom">
                <h5 class="font-weight-bold text-dark mb-1 mt-4">请先登录</h5>
            </div>
            <div class="overflow-hidden border-top">
                <a class="font-weight-bold p-3 d-block" href="{% url 'user:login' %}">登录</a>
            </div>
        </div>
    {% endif %}