TwitterDjango/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include  # url()
from django.views.generic import TemplateView
from django.views.static import serve

from article.views import home_view
from hotsearch.views import hot_search_list

urlpatterns = [
    path('', home_view, name='home'),
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('admin/', admin.site.urls),
    path('api/articles/', include(('article.urls', 'article'), namespace='article')),
    path('api/user/', include(('account.urls', 'account'), namespace='user')),
    path('api/profile/', include(('userprofile.urls', 'userprofile'), namespace='profile')),
    path('api/hotsearch', hot_search_list),
    re_path(r'.*', TemplateView.as_view(template_name='index.html'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path

from .views import (user_login,
                    user_logout,
                    user_register, user_change_password, send_reset_email, reset_password_2)

urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
    path('changepwd/', user_change_password, name='changepwd'),
    path('forgetpwd/', send_reset_email),
    path('resetpwd/', reset_password_2, name='reset')
]

tweetme2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include  # url()
from django.views.generic import TemplateView

from article.views import home_view

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    path('api/articles/', include(('article.urls', 'article'), namespace='article')),
    path('api/user/', include(('account.urls', 'account'), namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Login
{% endblock %}
{% block body_content %}
    <div class="bg-white">
         <div class="container">
            <div class="row justify-content-center align-items-center d-flex vh-100">
               <div class="col-md-4 mx-auto">
                  <div class="osahan-login py-4">
                     <div class="text-center mb-4">
                        <a href="{% url 'home' %}"><img alt="" src="{% static 'img/favicon.ico' %}" ></a>
                        <h5 class="font-weight-bold mt-3">欢迎回来</h5>
                        <p class="text-muted">期待与你一起分享美丽的世界</p>
                         <p class="text-danger ">{{ msg }}{{ errors }}</p>
                     </div>
                     <form action="{% url 'user:login' %}" method="post" >{% csrf_token %}
                        <div class="form-group">
                           <label class="mb-1">用户名</label>
                           <div class="position-relative icon-form-control">
                              <i class="feather-user position-absolute"></i>
                              <input type="text" name="username" class="form-control" required="">
                           </div>
                        </div>
                        <div class="form-group">
                           <label class="mb-1">密码</label>
                           <div class="position-relative icon-form-control">
                              <i class="feather-unlock position-absolute"></i>
                              <input type="password" name="password" class="form-control" required="">
                           </div>
                        </div>
                        <div class="custom-control custom-checkbox mb-3">
                           <input type="checkbox" class="custom-control-input" id="customCheck1">
                           <label class="custom-control-label" for="customCheck1">记住密码</label>
                        </div>
                         <button class="btn btn-primary btn-block text-uppercase" type="submit" name="login">登录</button>

                        <div class="py-3 d-flex align-item-center">
                           <a href="#">忘记密码？</a>
                           <span class="ml-auto"> 还没有账号？ <a class="font-weight-bold" href="{% url 'user:register' %}">注册</a></span>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Register
{% endblock %}
{% block body_content %}
    <div class="bg-white">
        <div class="container">
            <div class="row justify-content-center align-items-center d-flex vh-100">
                <div class="col-md-4 mx-auto">
                    <div class="osahan-login py-4">
                        <div class="text-center mb-4">
                            <a href="{% url 'home' %}"><img alt="" src={% static 'img/favicon.ico' %}></a>
                            <h5 class="font-weight-bold mt-3">注册</h5>
                            <p class="text-muted">进入WePost 记录你的美好生活</p>
                            <p>{{ msg }}</p>
                        </div>
                        <form action="{% url 'user:register' %}" method="post">{% csrf_token %}
                            <div class="form-group">
                                <label class="mb-1">用户名</label>
                                <div class="position-relative icon-form-control">
                                    <i class="feather-user position-absolute"></i>
                                    <input type="text" name="username" class="form-control" required="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="mb-1">电话</label>
                                <div class="position-relative icon-form-control">
                                    <i class="feather-phone position-absolute"></i>
                                    <input type="tel" name="phone_number" class="form-control" required="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="mb-1">邮箱</label>
                                <div class="position-relative icon-form-control">
                                    <i class="feather-at-sign position-absolute"></i>
                                    <input type="email" name="email" class="form-control" required="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="mb-1">密码(6位以上英文数字和特殊字符)</label>
                                <div class="position-relative icon-form-control">
                                    <i class="feather-unlock position-absolute"></i>
                                    <input type="password" name="password" class="form-control" id="password-1" required="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="mb-1">确认密码</label>
                                <div class="position-relative icon-form-control">
                                    <i class="feather-unlock position-absolute"></i>
                                    <input type="password" name="password" class="form-control" id="password-2" required="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="mb-1">我同意 <a href="#">用户守则</a>, <a href="#">隐私政策</a>和 <a href="#">Cookie
                                    政策</a>.</label>
                            </div>
                            <input class="btn btn-primary btn-block text-uppercase" type="submit"> 同意并继续</input>
                            <div class="py-3 d-flex align-item-center">
                                <a href="forgot-password.html">忘记密码？</a>
                                <span class="ml-auto"> 已有账号？ <a class="font-weight-bold" href="{% url 'user:login' %}">登录</a></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block myjs %}
    <script>
        window.onload = function () {
            document.getElementById("password-1").onchange = checkPwd;
            document.getElementById("password-2").onchange = validatePassword;
        };
        function checkPwd() {
            let pw1 = document.getElementById("password-1").value;
            let reg = /^(?![a-zA-z]+$)(?!\d+$)(?![!@#$%^&*]+$)[a-zA-Z\d!@#$%^&*]+$/;
            if (!reg.test(pw1)) {
                document.getElementById("password-1").setCustomValidity("密码不合法(6-18位字母、数字、特殊符号)");
                return false;
            } else {
                document.getElementById("password-1").setCustomValidity("");
            }
        }
        function validatePassword() {
            let pw1 = document.getElementById("password-1").value;
            let pw2 = document.getElementById("password-2").value;
            if (pw1 !== pw2) {
                document.getElementById("password-2").setCustomValidity("两次结果输入不一致");
            } else {
                document.getElementById("password-2").setCustomValidity("");
            }
        }</script>
{% endblock %}